/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JTextField;
import ejecucion.*;
/**
 *
 * @author Nicolás Velásquez
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */

    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonPrueba = new javax.swing.JButton();
        jButtonlvl3 = new javax.swing.JButton();
        jButtonlvl1 = new javax.swing.JButton();
        jButtonlvl2 = new javax.swing.JButton();
        scores = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 227, 215));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jButtonPrueba.setBackground(new java.awt.Color(234, 13, 205));
        jButtonPrueba.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonPrueba.setText("Prueba Inicial");
        jButtonPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPruebaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jButtonlvl3.setBackground(new java.awt.Color(246, 55, 55));
        jButtonlvl3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonlvl3.setText("Nivel 3");
        jButtonlvl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlvl3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jButtonlvl1.setBackground(new java.awt.Color(238, 223, 11));
        jButtonlvl1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonlvl1.setText("Nivel 1");
        jButtonlvl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlvl1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jButtonlvl2.setBackground(new java.awt.Color(19, 175, 230));
        jButtonlvl2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonlvl2.setText("Nivel 2");
        jButtonlvl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlvl2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        scores.setBackground(new java.awt.Color(83, 61, 233));
        scores.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        scores.setText("Puntajes");
        scores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresActionPerformed(evt);
            }
        });
        getContentPane().add(scores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPruebaActionPerformed
        Pantalla.puntaje = 0;
        Pantalla.lifes = 3;
        dispose();
        Eleccion ele = new Eleccion(1,true);
        ele.setVisible(true);
        
    }//GEN-LAST:event_jButtonPruebaActionPerformed

    private void jButtonlvl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlvl1ActionPerformed
        Pantalla.puntaje = 0;
        Pantalla.lifes = 3;
        dispose();
        Eleccion ele = new Eleccion(1,false);
        ele.setVisible(true);
       
    }//GEN-LAST:event_jButtonlvl1ActionPerformed

    private void jButtonlvl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlvl2ActionPerformed
        Pantalla.puntaje = 0;
        Pantalla.lifes = 3;
        dispose();
        Eleccion ele = new Eleccion(2,false);
        ele.setVisible(true);
    }//GEN-LAST:event_jButtonlvl2ActionPerformed

    private void jButtonlvl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlvl3ActionPerformed
        Pantalla.puntaje = 0;
        Pantalla.lifes = 3;
        dispose();
        Eleccion ele = new Eleccion(3,false);
        ele.setVisible(true);
    }//GEN-LAST:event_jButtonlvl3ActionPerformed

    private void scoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresActionPerformed
        ArrayList<Integer> sc = new ArrayList<>();
        sc = getScores();
        Collections.sort(sc);
        Collections.reverse(sc);
        String cur = "";
        for (Integer a : sc) {
            cur += a + "\n";
        }
        JOptionPane.showMessageDialog(null, cur, "Puntajes ordenados descendentemente",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_scoresActionPerformed

    public ArrayList<Integer> getScores(){
         ArrayList<Integer> current = new ArrayList<Integer>();
         current.clear();
         int iteratorRead = 1;
         try{
         File myFile = new File("Scores.txt");
         
         FileReader fileReader = new FileReader(myFile);
         BufferedReader reader = new BufferedReader(fileReader);
         
         String line = null;
         while((line = reader.readLine()) !=null){
             
             JTextField currentJText = new JTextField();
             //currentJText = assignTextFieldSerializable(iteratorRead);
             currentJText.setText(line);
             current.add(Integer.parseInt(line));
             //Se creo un metodo automatico en esta clase pero se debe
             //implementar el que está en MiddleInterface.
             System.out.print("\n"+ line);
              
         }
         
         
         }
          catch (FileNotFoundException ax){
            System.out.println("Archivo no encontrado");
        } catch (IOException ax) {
           //Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ax);
           System.out.print("No se puede leer del archivo");
        }
         finally{
          //  System.out.print("\nSe ha ejecutado el metodo Plain Text");
         }
         return current;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrueba;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonlvl1;
    private javax.swing.JButton jButtonlvl2;
    private javax.swing.JButton jButtonlvl3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JButton scores;
    // End of variables declaration//GEN-END:variables
}
